#!/usr/bin/env python3

#######################
# This file is a part #
#   of the deepmage   #
#  project, released  #
# under the GNU GPL 3 #
#      license        #
#  (see the COPYING   #
#  file for details)  #
#######################

import argparse
import libdeepmage.deepmage

parser = argparse.ArgumentParser("deepmage")
parser.add_argument('filename', metavar='file', type=str, help='Path to a file to edit')
args = parser.parse_args()

libdeepmage.deepmage.main(args.filename)
