#!/usr/bin/env python3

#######################
# This file is a part #
#   of the deepmage   #
#  project, released  #
# under the GNU GPL 3 #
#      license        #
#  (see the COPYING   #
#  file for details)  #
#######################

import hy
import argparse
import libdeepmage.bitstream_reader
from libdeepmage.deepmage import hex_representation, bit_representation

parser = argparse.ArgumentParser("deepmage-hexdump")
parser.add_argument('filename', metavar='file', type=str, help='Path to a file to edit')
args = parser.parse_args()

with open(args.filename, 'rb') as f:
    reader = libdeepmage.bitstream_reader.FileReader(f, 1024)
    for i in range(0, reader.get_wordcount(), 16):
        view = reader.get_view(i, 16)
        print(''.join([hex_representation(view[j]) + ' ' for j in range(16)]))
